/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonHistoireRouteImport } from './routes/mon-histoire'
import { Route as IndexRouteImport } from './routes/index'

const MonHistoireRoute = MonHistoireRouteImport.update({
  id: '/mon-histoire',
  path: '/mon-histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mon-histoire': typeof MonHistoireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mon-histoire': typeof MonHistoireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mon-histoire': typeof MonHistoireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mon-histoire'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mon-histoire'
  id: '__root__' | '/' | '/mon-histoire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MonHistoireRoute: typeof MonHistoireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mon-histoire': {
      id: '/mon-histoire'
      path: '/mon-histoire'
      fullPath: '/mon-histoire'
      preLoaderRoute: typeof MonHistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MonHistoireRoute: MonHistoireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
